/**
 * Every string on the site. English is the launch language; Russian is drafted
 * and marked pending owner review. Nothing here may assert a claim the research
 * package has not cleared (no history, no certification, no superlatives, no
 * "signature dish", no service promises).
 */

export type Lang = 'en' | 'ru';

export const COPY = {
  en: {
    approval: {
      status: 'draft_owner_approval_required',
      note: 'Draft website copy; written restaurant approval is required before production.',
    },
    meta: {
      title: 'Padishah Restaurant — 1920 Avenue U, Brooklyn',
      description: 'Padishah Restaurant at 1920 Avenue U, Brooklyn, NY 11229. Call (718) 743-9656 or open directions.',
    },
    review: {
      banner: 'Website preview — menu, media and details are pending the restaurant’s approval.',
      bannerShort: 'Preview build',
      badgeReviewOnly: 'Review only',
      badgeRelease: 'Release required',
      mediaNote: 'Research preview image. Final photography to be supplied by the restaurant.',
      verifiedToggle: 'What is verified?',
      checked:
        'Checked {date}. Hours, menu, prices, cuisine wording and the halal statement come from public sources and still need the restaurant’s confirmation.',
      verifiedLabels: {
        name: 'Name',
        address: 'Address',
        phone: 'Phone',
        instagram: 'Instagram',
        directions: 'Directions',
      },
      directionsValue: 'Google Maps',
    },
    nav: {
      menu: 'Menu',
      fire: 'The fire',
      room: 'The room',
      banquets: 'Banquets',
      visit: 'Visit',
      call: 'Call',
      directions: 'Directions',
      skip: 'Skip to content',
      mainLabel: 'Main navigation',
      footerLabel: 'Footer navigation',
    },
    hero: {
      eyebrow: '1920 Avenue U · Brooklyn',
      title: 'Off the fire,\nonto the table.',
      sub: 'Skewers over coals, then straight to a wooden board — at 1920 Avenue U in Brooklyn.',
      ctaMenu: 'View the menu',
      ctaCall: 'Call (718) 743-9656',
      scroll: 'Scroll',
      pause: 'Pause background video',
      play: 'Play background video',
      optionBTitle: 'The table is ready at Padishah.',
      optionBBody:
        'Come for smoke-kissed kebabs, samsa, manti, fresh salads, and generous plates made for sharing.',
    },
    fire: {
      eyebrow: 'From the grill',
      title: 'It starts at the coals.',
      body: 'Lamb ribs, lulya, liver and chicken go over the fire on long skewers, then straight to a wooden board with red onion, lemon and herbs. That short walk from the grill to your table is the whole idea.',
      deckTitle: 'From the grill to the table',
      deckBody:
        'The Padishah experience begins with heat, smoke, and food meant to be shared. Discover lamb ribs, lulya kebab, samsa, manti, achichuk, soups, fish, and comforting sides.',
    },
    dishes: {
      eyebrow: 'On the table',
      title: 'What people come back for.',
      body: 'Drawn from the restaurant’s public menu. The owner has not yet chosen a signature list, so nothing here is presented as one.',
      cta: 'See the full menu',
    },
    room: {
      eyebrow: 'The room',
      title: 'A table long enough for everyone.',
      body: 'The restaurant announced a renewed dining room in June 2026. It is a room for a Tuesday dinner and for the kind of evening where the table keeps growing.',
      note: 'Room and event details are being confirmed with the restaurant.',
      deckTitle: 'A renewed room for everyday dinners and big tables',
      deckBody: 'Join us on Avenue U for a relaxed meal with family and friends.',
      deckEventsDraft: 'For group dining or celebrations, call and let our team help plan the table.',
    },
    menuPreview: {
      eyebrow: 'The menu',
      title: 'Nine sections, forty-two dishes.',
      body: 'Salads, soups, cold and hot appetisers, mains, shish kebab, fish, sides and drinks.',
    },
    ratings: {
      eyebrow: 'In public',
      title: 'What the listings say.',
      note: 'Public platform ratings, observed {date}. They move; check the source.',
    },
    visit: {
      eyebrow: 'Visit',
      title: 'Find us on Avenue U.',
      hoursLabel: 'Hours',
      hoursNote: 'Public listing hours — please call to confirm.',
      addressLabel: 'Address',
      phoneLabel: 'Phone',
      directions: 'Open in Google Maps',
      instagram: 'Instagram',
      order: 'Order online',
      orderNote: 'Grubhub listing found in research. The restaurant has not yet chosen its official ordering link.',
      // Calendar labels for the day keys in the hours data — labels, not facts.
      days: {
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
        saturday: 'Saturday',
        sunday: 'Sunday',
      },
    },
    menuPage: {
      title: 'Menu',
      lead: 'The full public menu, kept in structured data so it can be corrected in one place.',
      notice:
        'Menu and prices are being confirmed with the restaurant. No confirmed prices are published yet — please call for today’s menu and availability.',
      observed: 'Snapshot observed {date} · source: {source}',
      search: 'Search dishes',
      searchPlaceholder: 'kebab, samsa, salad…',
      empty: 'Nothing matched. Try a shorter word, or call the restaurant.',
      priceUnavailable: 'Call for price',
      all: 'All',
      noteNameSuggested: 'Spelling to be confirmed',
      noteDescriptionPending: 'Description to be confirmed',
      notePossibleDuplicate: 'Appears twice in the public listing',
      notePriceUnavailable: 'Price not published',
      notePendingOwner: 'Pending confirmation',
      countLabel: '{n} dishes',
      showResearchPrices: 'Show the prices we found ({date})',
      hideResearchPrices: 'Hide the researched prices',
      researchPriceNote:
        'These are the prices published on a delivery listing on {date}, shown for review only. They are not the restaurant’s confirmed prices.',
      researchPriceTag: 'Researched',
      categoryApproval: 'Category pending restaurant confirmation',
      itemApproval: 'Menu item pending restaurant confirmation',
    },
    concierge: {
      open: 'Help me choose',
      title: 'What are you in the mood for?',
      lead: 'This picks from the dishes on this page. It knows nothing the menu does not say.',
      placeholder: 'grilled lamb for four…',
      submit: 'Show me',
      refusal:
        'The menu data does not answer that. Halal, allergens, spice level and dietary questions have to come from the restaurant — please call (718) 743-9656.',
      empty: 'Nothing on the published menu matches that. Try another word.',
      resultsLabel: 'Suggested from the menu',
    },
    footer: {
      rights: 'Preview build — not a public website.',
      pendingTitle: 'Still pending the restaurant’s approval',
      langLabel: 'Language',
      factsChecked: 'Facts checked {date}.',
      pendingItems: [
        'Current hours',
        'Canonical cuisine wording',
        'Halal wording and any certification',
        'Reservation process',
        'Canonical ordering link',
        'Service modes',
        'Private-events offering',
        'Launch languages',
        'Current legal/business name',
        'Current logo master and brand colors',
      ],
    },
    menuCategories: {
      salads: 'Salads',
      soups: 'Soups',
      'cold-appetizers': 'Cold Appetizers',
      'main-course': 'Main Course',
      'shish-kebab': 'Shish Kebab',
      'fish-dishes': 'Fish Dishes',
      'side-dishes': 'Side Dishes',
      'cold-beverages': 'Cold Beverages',
      'hot-appetizers': 'Hot Appetizers',
    },
  },

  ru: {
    approval: {
      status: 'draft_owner_approval_required',
      note: 'Черновик текста сайта; до публикации требуется письменное подтверждение ресторана.',
    },
    meta: {
      title: 'Ресторан «Падишах» — 1920 Avenue U, Бруклин',
      description: 'Ресторан «Падишах» по адресу 1920 Avenue U, Brooklyn, NY 11229. Телефон (718) 743-9656.',
    },
    review: {
      banner: 'Превью сайта — меню, фото и детали ждут подтверждения ресторана.',
      bannerShort: 'Превью',
      badgeReviewOnly: 'Только для превью',
      badgeRelease: 'Нужно согласие людей в кадре',
      mediaNote: 'Изображение из исследования. Финальные фото предоставит ресторан.',
      verifiedToggle: 'Что проверено?',
      checked:
        'Проверено {date}. Часы, меню, цены, формулировка кухни и заявление о халяль взяты из публичных источников и требуют подтверждения ресторана.',
      verifiedLabels: {
        name: 'Название',
        address: 'Адрес',
        phone: 'Телефон',
        instagram: 'Instagram',
        directions: 'Маршрут',
      },
      directionsValue: 'Google Maps',
    },
    nav: {
      menu: 'Меню',
      fire: 'Огонь',
      room: 'Зал',
      banquets: 'Банкеты',
      visit: 'Как найти',
      call: 'Позвонить',
      directions: 'Маршрут',
      skip: 'К содержимому',
      mainLabel: 'Основная навигация',
      footerLabel: 'Навигация в подвале',
    },
    hero: {
      eyebrow: '1920 Avenue U · Бруклин',
      title: 'С огня —\nсразу на стол.',
      sub: 'Шашлык над углями, а потом сразу на деревянную доску — 1920 Avenue U, Бруклин.',
      ctaMenu: 'Посмотреть меню',
      ctaCall: 'Позвонить (718) 743-9656',
      scroll: 'Вниз',
      pause: 'Остановить видео',
      play: 'Включить видео',
      optionBTitle: 'Стол накрыт — добро пожаловать в Падишах.',
      optionBBody: 'Шашлык, самса, манты, свежие салаты и щедрые блюда, которыми хочется делиться.',
    },
    fire: {
      eyebrow: 'С мангала',
      title: 'Всё начинается с углей.',
      body: 'Рёбрышки ягнёнка, люля, печень и курица уходят на огонь, а потом сразу на деревянную доску — с красным луком, лимоном и зеленью. Этот короткий путь от мангала до стола и есть вся идея.',
      deckTitle: 'С огня — прямо к столу',
      deckBody:
        'Вкус Падишаха начинается с жара мангала, аромата дыма и блюд для общего стола. В меню — шашлык, рёбрышки ягнёнка, люля-кебаб, самса, манты, ачичук, супы, рыба и домашние гарниры.',
    },
    dishes: {
      eyebrow: 'На столе',
      title: 'За чем возвращаются.',
      body: 'Составлено по публичному меню ресторана. Владелец ещё не выбрал фирменные блюда, поэтому ничего здесь так не называется.',
      cta: 'Открыть меню',
    },
    room: {
      eyebrow: 'Зал',
      title: 'Стол, за который поместятся все.',
      body: 'В июне 2026 года ресторан объявил об обновлении зала. Это зал и для ужина во вторник, и для вечера, когда стол всё растёт.',
      note: 'Детали по залу и праздникам уточняются у ресторана.',
      deckTitle: 'Обновлённый зал для семейных ужинов и больших компаний',
      deckBody: 'Ждём вас на Avenue U.',
      deckEventsDraft: 'Чтобы обсудить большой стол или праздник, позвоните нам.',
    },
    menuPreview: {
      eyebrow: 'Меню',
      title: 'Девять разделов, сорок два блюда.',
      body: 'Салаты, супы, холодные и горячие закуски, горячее, шашлык, рыба, гарниры и напитки.',
    },
    ratings: {
      eyebrow: 'Публично',
      title: 'Что показывают площадки.',
      note: 'Публичные оценки на {date}. Они меняются — смотрите источник.',
    },
    visit: {
      eyebrow: 'Визит',
      title: 'Мы на Avenue U.',
      hoursLabel: 'Часы',
      hoursNote: 'Часы из публичного справочника — уточните по телефону.',
      addressLabel: 'Адрес',
      phoneLabel: 'Телефон',
      directions: 'Открыть в Google Maps',
      instagram: 'Instagram',
      order: 'Заказать онлайн',
      orderNote: 'Ссылка на Grubhub найдена в исследовании. Ресторан ещё не выбрал официальную площадку для заказов.',
      // Названия дней недели для ключей в данных о часах — подписи, не факты.
      days: {
        monday: 'Понедельник',
        tuesday: 'Вторник',
        wednesday: 'Среда',
        thursday: 'Четверг',
        friday: 'Пятница',
        saturday: 'Суббота',
        sunday: 'Воскресенье',
      },
    },
    menuPage: {
      title: 'Меню',
      lead: 'Полное публичное меню — в структурированных данных, чтобы правки вносились в одном месте.',
      notice:
        'Меню и цены уточняются у ресторана. Подтверждённых цен пока нет — пожалуйста, звоните, чтобы узнать сегодняшнее меню и наличие.',
      observed: 'Снимок от {date} · источник: {source}',
      search: 'Поиск по блюдам',
      searchPlaceholder: 'шашлык, самса, салат…',
      empty: 'Ничего не нашлось. Попробуйте короче или позвоните в ресторан.',
      priceUnavailable: 'Цену уточняйте',
      all: 'Все',
      noteNameSuggested: 'Написание уточняется',
      noteDescriptionPending: 'Описание уточняется',
      notePossibleDuplicate: 'Встречается в листинге дважды',
      notePriceUnavailable: 'Цена не опубликована',
      notePendingOwner: 'Ждёт подтверждения',
      countLabel: 'блюд: {n}',
      showResearchPrices: 'Показать найденные цены ({date})',
      hideResearchPrices: 'Скрыть найденные цены',
      researchPriceNote:
        'Это цены с публичной страницы доставки на {date}, показаны только для проверки. Ресторан их не подтверждал.',
      researchPriceTag: 'Из исследования',
      categoryApproval: 'Раздел ждёт подтверждения ресторана',
      itemApproval: 'Блюдо ждёт подтверждения ресторана',
    },
    concierge: {
      open: 'Помочь выбрать',
      title: 'Чего хочется?',
      lead: 'Подбор идёт только по блюдам с этой страницы. Ничего сверх меню он не знает.',
      placeholder: 'баранина на четверых…',
      submit: 'Показать',
      refusal:
        'В данных меню нет такого ответа. Про халяль, аллергены, остроту и диеты может сказать только ресторан — позвоните: (718) 743-9656.',
      empty: 'В опубликованном меню совпадений нет. Попробуйте другое слово.',
      resultsLabel: 'Подобрано из меню',
    },
    footer: {
      rights: 'Превью-сборка — не публичный сайт.',
      pendingTitle: 'Ждёт подтверждения ресторана',
      langLabel: 'Язык',
      factsChecked: 'Данные проверены {date}.',
      pendingItems: [
        'Актуальные часы работы',
        'Основная формулировка кухни',
        'Формулировка о халяль и возможная сертификация',
        'Порядок бронирования',
        'Официальная ссылка для заказов',
        'Форматы обслуживания',
        'Услуги для частных мероприятий',
        'Языки сайта',
        'Актуальное юридическое и публичное название',
        'Мастер-файл логотипа и фирменные цвета',
      ],
    },
    menuCategories: {
      salads: 'Салаты',
      soups: 'Супы',
      'cold-appetizers': 'Холодные закуски',
      'main-course': 'Горячие блюда',
      'shish-kebab': 'Шашлык',
      'fish-dishes': 'Рыбные блюда',
      'side-dishes': 'Гарниры',
      'cold-beverages': 'Холодные напитки',
      'hot-appetizers': 'Горячие закуски',
    },
  },
} as const;

export type CopyBundle = (typeof COPY)['en'];

export const fill = (s: string, vars: Record<string, string | number>) =>
  s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`));
