#!/usr/bin/env node
/**
 * build-content.mjs — the ONLY bridge between the research package and the website.
 *
 * Reads the structured research files, emits typed TypeScript modules into
 * src/content/generated/. Nothing in the app hand-copies research values.
 *
 * Hard rules enforced here:
 *  - data/nyc-health-snapshot.json is never opened (private launch due diligence).
 *  - Every emitted value carries its approval status.
 *  - price_cents === 0 is emitted as null + a flag, never as a $0.00 price.
 *  - Media entries carry rights status and production_approved verbatim from the manifest.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = resolve(HERE, '..');
const RESEARCH = resolve(APP, '../website-research');
const OUT = resolve(APP, 'src/content/generated');

const FORBIDDEN_SOURCE = 'nyc-health-snapshot';

const read = (rel) => {
  if (rel.includes(FORBIDDEN_SOURCE)) {
    throw new Error(`Refusing to read private launch file: ${rel}`);
  }
  return JSON.parse(readFileSync(resolve(RESEARCH, rel), 'utf8'));
};

const facts = read('data/business-facts.json');
const menu = read('data/public-menu-snapshot.json');
const reviews = read('data/review-snapshot.json');
const approvals = read('data/production-approvals.json');
const manifest = read('media-library/manifest.json');
const altText = read('media-library/site-alt-text.json');

const banner = (name) =>
  `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.\n` +
  `// Source: website-research/${name}\n` +
  `// Research observed_at: ${facts.observed_at}\n\n`;

const j = (v) => JSON.stringify(v, null, 2);

mkdirSync(OUT, { recursive: true });

/* ------------------------------------------------------------------ facts */

const b = facts.business;
const hoursApproved =
  typeof approvals.current_hours?.approved_at === 'string' &&
  approvals.current_hours?.days &&
  typeof approvals.current_hours.days === 'object' &&
  !Array.isArray(approvals.current_hours.days);
const currentHours = hoursApproved ? approvals.current_hours.days : b.hours_observed_google;
const factsModule =
  banner('data/business-facts.json') +
  `import type { Fact, Hours } from '../types';\n\n` +
  `export const OBSERVED_AT = ${j(facts.observed_at)} as const;\n\n` +
  `/** Only these may be presented to a guest as verified. */\n` +
  `export const VERIFIED = {\n` +
  `  name: ${j(b.canonical_name)},\n` +
  `  street: ${j(b.address.street)},\n` +
  `  city: ${j(b.address.city)},\n` +
  `  state: ${j(b.address.state)},\n` +
  `  postalCode: ${j(b.address.postal_code)},\n` +
  `  country: ${j(b.address.country)},\n` +
  `  addressLine: ${j(`${b.address.street}, ${b.address.city}, ${b.address.state} ${b.address.postal_code}`)},\n` +
  `  phoneE164: ${j(b.phone_e164)},\n` +
  `  phoneDisplay: ${j(b.phone_display)},\n` +
  `  instagram: ${j(b.official_instagram)},\n` +
  `  directions: ${j(b.google_maps)},\n` +
  `} as const;\n\n` +
  `/** Provisional: shown only with its approval state visible. */\n` +
  `export const PROVISIONAL: Record<string, Fact> = ${j({
    cuisine: {
      value: b.recommended_canonical_cuisine_copy,
      status: 'research_only',
      source: 'Google category + NYC DOHMH category, reconciled in research',
      verifiedAt: facts.observed_at,
    },
    hoursSummary: {
      value: hoursApproved ? approvals.current_hours.summary : '10:00 AM – 10:00 PM',
      status: hoursApproved ? 'owner_confirmed' : 'research_only',
      source: hoursApproved ? 'Written restaurant approval' : 'Google Maps public listing snapshot',
      verifiedAt: hoursApproved ? approvals.current_hours.approved_at : facts.observed_at,
    },
    orderLink: {
      value: b.grubhub,
      status: 'research_only',
      source: 'Grubhub public listing; owner has not chosen a canonical destination',
      verifiedAt: facts.observed_at,
    },
    reservations: {
      value: b.reservations.provisional_method,
      status: 'research_only',
      source: 'Instagram mentions table booking; process unconfirmed',
      verifiedAt: facts.observed_at,
    },
    relaunch: {
      value: b.relaunch.announced_opening,
      status: 'research_only',
      source: 'Official Instagram grand-opening announcement',
      verifiedAt: facts.observed_at,
    },
    halal: {
      value: b.halal_claim.claim,
      status: 'blocked',
      source: 'First-party poster claim, no independent certification found',
      verifiedAt: facts.observed_at,
    },
  })};\n\n` +
  `export const HOURS: Hours = ${j({
    status: hoursApproved ? 'owner_confirmed' : b.hours_status,
    verifiedAt: hoursApproved ? approvals.current_hours.approved_at : facts.observed_at,
    days: Object.entries(currentHours).map(([day, value]) => ({ day, value })),
  })};\n\n` +
  `/** Explicit owner approvals. Null values intentionally keep production fail-closed. */\n` +
  `export const PRODUCTION_APPROVALS = ${j(approvals)} as const;\n\n` +
  `export const MUST_CONFIRM_BEFORE_LAUNCH = ${j(facts.must_confirm_before_launch)} as const;\n`;

writeFileSync(resolve(OUT, 'facts.ts'), factsModule);

/* ------------------------------------------------------------------- menu */

const FLAG_NOTE = {
  invalid_price: 'price_unavailable',
  owner_confirmation_required: 'pending_owner',
  normalized_name_suggestion: 'name_suggested',
  transliteration_owner_confirmation_required: 'name_suggested',
  dish_name_owner_confirmation_required: 'name_suggested',
  dish_name_and_description_owner_confirmation_required: 'name_suggested',
  description_owner_confirmation_required: 'description_pending',
  brand_and_size_owner_confirmation_required: 'pending_owner',
  possible_duplicate_owner_confirmation_required: 'possible_duplicate',
};

const menuApproved = typeof approvals.menu?.approved_at === 'string' && approvals.menu.approved_at.length > 0;

const items = menu.items.map((it) => {
  const priceInvalid = !it.price_cents || it.flags.includes('invalid_price');
  // Fall back to the normalised name when the published name is not Latin (e.g. "Гужа").
  const slug = (v) =>
    (v ?? '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
  const id = `${it.category_id}--${slug(it.raw_name) || slug(it.display_name)}`;
  if (id.endsWith('--')) throw new Error(`Menu item has no stable name in category ${it.category_id}`);
  return {
    id,
    categoryId: it.category_id,
    rawName: it.raw_name,
    displayName: it.display_name,
    approval: menuApproved ? 'owner_confirmed' : 'research_only',
    ownerConfirmationRequired: !menuApproved,
    // Research prices remain available for audit, but never become public prices
    // until the owner approves this exact menu snapshot.
    researchPriceCents: priceInvalid ? null : it.price_cents,
    priceCents: menuApproved && !priceInvalid ? it.price_cents : null,
    priceStatus: priceInvalid ? 'blocked' : menuApproved ? 'owner_confirmed' : 'research_only',
    description: it.description,
    featured: it.featured,
    flags: it.flags,
    notes: [...new Set(it.flags.map((f) => FLAG_NOTE[f]).filter(Boolean))],
  };
});

const zeroPriced = items.filter((i) => i.priceCents === 0 || i.researchPriceCents === 0);
if (zeroPriced.length) {
  throw new Error(`Zero-priced items leaked into generated menu: ${zeroPriced.map((i) => i.rawName).join(', ')}`);
}

writeFileSync(
  resolve(OUT, 'menu.ts'),
  banner('data/public-menu-snapshot.json') +
    `import type { MenuCategory, MenuItem } from '../types';\n\n` +
    `export const MENU_STATUS = ${j(menu.status)} as const;\n` +
    `export const MENU_OBSERVED_AT = ${j(menu.observed_at)} as const;\n` +
    `export const MENU_APPROVED_AT: string | null = ${j(approvals.menu?.approved_at ?? null)};\n` +
    `export const MENU_SOURCE = ${j(menu.source)} as const;\n` +
    `export const MENU_NOTES = ${j(menu.notes)} as const;\n\n` +
    `export const CATEGORIES: MenuCategory[] = ${j(
      menu.categories
        .slice()
        .sort((a, x) => a.sort - x.sort)
        .map((c) => ({
          id: c.id,
          name: c.name,
          sort: c.sort,
          approval: menuApproved ? 'owner_confirmed' : 'research_only',
          ownerConfirmationRequired: !menuApproved,
        })),
    )};\n\n` +
    `export const ITEMS: MenuItem[] = ${j(items)};\n`,
);

/* ---------------------------------------------------------------- ratings */

writeFileSync(
  resolve(OUT, 'ratings.ts'),
  banner('data/review-snapshot.json') +
    `import type { RatingSnapshot } from '../types';\n\n` +
    `export const RATINGS_OBSERVED_AT = ${j(reviews.observed_at)} as const;\n\n` +
    `export const RATINGS: RatingSnapshot[] = ${j(
      reviews.ratings
        .filter((r) => typeof r.rating === 'number')
        .map((r) => ({
          platform: r.platform,
          rating: r.rating,
          reviewCount: r.review_count,
          url: r.url,
          observedAt: reviews.observed_at,
        })),
    )};\n\n` +
    `/** Research synthesis. Never rendered as a customer quote. */\n` +
    `export const POSITIVE_THEMES = ${j(reviews.positive_themes)} as const;\n`,
);

/* ------------------------------------------------------------------ media */

const derivPath = resolve(APP, 'public/media/derivatives.json');
const derivatives = existsSync(derivPath) ? JSON.parse(readFileSync(derivPath, 'utf8')) : { assets: {} };

const idOf = (p) =>
  `${p.split('/')[1]}/${basename(p, extname(p))
    .replace(/-(review-only|release-required)$/, '')
    .replace(/[^a-z0-9]+/gi, '-')
    .toLowerCase()}`;

const selected = manifest.files
  .filter((f) => f.path.startsWith('selected/'))
  .map((f) => {
    const id = idOf(f.path);
    const d = derivatives.assets?.[id] ?? null;
    return {
      id,
      kind: f.kind,
      sourcePath: f.path,
      width: f.width,
      height: f.height,
      durationSeconds: f.duration_seconds,
      rightsStatus: f.rights_status,
      productionApproved: f.production_approved,
      curationLabel: f.curation_label,
      sourceUrl: f.source_url,
      qualityFlags: f.quality_flags ?? [],
      alt: altText.alt?.[id] ?? null,
      // Web derivatives produced by scripts/build-media.mjs (null until that runs).
      web: d,
    };
  })
  .sort((a, x) => a.id.localeCompare(x.id));

/**
 * Cuts produced by build-media (e.g. motion/fire) are new assets derived from a library
 * file. They inherit the source's rights verbatim — deriving a clip grants nothing.
 */
const byPath = Object.fromEntries(manifest.files.map((f) => [f.path, f]));
const derived = Object.entries(derivatives.assets ?? {})
  .filter(([id]) => !selected.some((a) => a.id === id))
  .map(([id, web]) => {
    const parent = byPath[web.derivedFrom];
    if (!parent) throw new Error(`Derivative "${id}" claims an unknown source: ${web.derivedFrom}`);
    return {
      id,
      kind: parent.kind,
      sourcePath: parent.path,
      width: web.poster?.width ?? parent.width,
      height: web.poster?.height ?? parent.height,
      durationSeconds: web.durationSeconds ?? parent.duration_seconds,
      rightsStatus: parent.rights_status,
      productionApproved: parent.production_approved,
      curationLabel: parent.curation_label,
      sourceUrl: parent.source_url,
      qualityFlags: parent.quality_flags ?? [],
      alt: altText.alt?.[id] ?? null,
      web,
    };
  });

selected.push(...derived);
selected.sort((a, x) => a.id.localeCompare(x.id));

const leaked = selected.filter((a) => a.productionApproved === true);
writeFileSync(
  resolve(OUT, 'media.ts'),
  banner('media-library/manifest.json') +
    `import type { MediaAsset } from '../types';\n\n` +
    `export const MEDIA_PRODUCTION_GATE = ${j(manifest.production_gate)} as const;\n\n` +
    `export const MEDIA: Record<string, MediaAsset> = ${j(
      Object.fromEntries(selected.map((a) => [a.id, a])),
    )};\n\n` +
    `export const PRODUCTION_CLEARED_COUNT = ${leaked.length};\n`,
);

console.log(
  `content: ${items.length} menu items / ${menu.categories.length} categories, ` +
    `${selected.length} media assets (${selected.filter((a) => a.web).length} with web derivatives), ` +
    `${JSON.parse(j(reviews.ratings)).length} rating snapshots -> src/content/generated/`,
);
